[package]
name = "matrix_bot"
version = "0.1.0"
authors = ["zwieberl <donko@posteo.de>"]


[dependencies]
matrix_bot_api = "*"
config = "0.8"
# dice handler
rand = "0.3"
# Weather handler
serde_json = "1.0"
reqwest = "*"
chrono = "*"

[dependencies.openweathermap_api]
path = "./openweathermap_api"